FROM rust:1.89-bullseye

# Set system environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich


WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
git

# Avoid caching issues
ARG commit_hash
RUN echo "Cloning grcov repository at commit: ${commit_hash}"

# Clone the grcov repository
RUN git clone https://github.com/mozilla/grcov.git /app/grcov


# Set repository specific variables
# Check with Konstantinos, since it depends on the programming language

WORKDIR /app/grcov

# Checkout the specific commit
RUN git checkout ${commit_hash}

RUN cargo build --release

CMD ["tail", "-f", "/dev/null"]






